export const REMOVE_TO_DO_LIST = 'REMOVE_TO_DO_LIST'
export const ADD_TO_DO_LIST = 'ADD_TO_DO_LIST'
export const FILTER_TASKS = 'FILTER_TASKS'
export const REMOVE_TASK = 'REMOVE_TASK'
export const ADD_TASK = 'ADD_TASK'
export const CHANGE_STATUS_TASK = 'CHANGE_STATUS_TASK'
export const CHANGE_TASK = 'CHANGE_TASK'
export const CHANGE_TITLE_TO_DO_LIST = 'CHANGE_TITLE_TO_DO_LIST'

